name : Github Actions 실행 테스트

on:
  push:
    branches:
      - main

jobs:
    My-Deploy-job:
      runs-on: ubuntu-latest

      steps:
        - name: Hello World 찍기
        run: echo "Hello World"